name: Check versions

on:
  schedule:
    - cron: '0 7 * * *'

jobs:
  check-versions:
    name: Check for new versions
    runs-on: ubuntu-latest
    outputs:
      added-versions: ${{ steps.check-versions.outputs.added-versions }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - name: Check for new versions
        id: check-versions
        run: |
          set -o pipefail
          added_versions=$(npm run check-versions-ts | tee /dev/fd/2 | (grep -oP '(?<=\[\[).*(?=\]\])' || echo))
          echo "added-versions=$added_versions" >>$GITHUB_OUTPUT

      - uses: actions/upload-artifact@v4
        with:
          name: fasm_versions.json
          path: ./fasm_versions.json
          retention-days: 1

  pull-request:
    name: Test & create pull request
    needs: check-versions
    if: needs.check-versions.outputs.added-versions != ''
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: fasm_versions.json

      - name: Test install latest fasm 1 version
        if: contains(needs.check-versions.outputs.added-versions, 'fasm1')
        uses: stevenwdv/setup-fasm@v1
        with:
          edition: fasm1
          fallback-to-previous-compatible: false
          custom-version-list: ./fasm_versions.json
      - name: Test install latest fasm g version
        if: contains(needs.check-versions.outputs.added-versions, 'fasmg')
        uses: stevenwdv/setup-fasm@v1
        with:
          edition: fasmg
          fallback-to-previous-compatible: false
          custom-version-list: ./fasm_versions.json

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          add-paths: fasm_versions.json
          commit-message: Add ${{ needs.check-versions.outputs.added-versions }} to fasm_versions.json
          author: Version checker bot <41898282+github-actions[bot]@users.noreply.github.com>
          branch: fasm-version-updates
          delete-branch: true
          title: Update fasm_versions.json
          body: Add ${{ needs.check-versions.outputs.added-versions }} to fasm_versions.json
          labels: fasm-versions
